### ISSUE TITLE
Can't resolve the dependencies of mdb-agg-crewai

### ISSUE THREAD

**Issue by vimalkansal** [ranfysvalle02/mdb-agg-crewai#1]
Hi there,

I am having hardtime resolving the dependcies mentioned in requirements.txt. My project is a poetry project and Python is at 3.11. Till this stage :

python = ">=3.11,<=3.13"
pymongo = "4.7.2"
crewai = "0.22.5"

it works alright. but the momemnt I try adding langchain==0.2.1 I get this :

poetry add langchain@0.2.1          

Updating dependencies
Resolving dependencies... (0.0s)

Because mongodbcreaiaggr depends on crewai (0.22.5) which depends on langchain (>=0.1.10,<0.2.0), langchain is required.
So, because mongodbcreaiaggr depends on langchain (0.2.1), version solving failed.  Can you please update reequirements.txt file

**Comment by ranfysvalle02** [comment]
@vimalkansal - You are absolutely right! I will fix and re-upload shortly

**Comment by ranfysvalle02** [comment]
Updated requirements.txt, and also added a Notebook that you can run/test ;)

https://github.com/ranfysvalle02/mdb-agg-crewai/blob/main/crewai-mdb-agg.ipynb
